name: comfort_sleep
description: ...

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc: ^6.0.0
  audioplayers: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/sounds/ocean.mp3
   - assets/sounds/rain.mp3
   - assets/sounds/underwater.mp3
